base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from base.views import principal, principal_admin, agendar_cita





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',principal,name="index"),
    path('adm',principal_admin,name="index-admin"),
    path('comunidad/',include('comunidad.urls')),
    path('agendar_cita/', agendar_cita, name='agendar_cita'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comunidad/urls.py
from django.urls import path
from comunidad.views import usuario_crear,usuario_eliminar,usuario_editar

urlpatterns = [
    path("usuarios/", usuario_crear, name="usuarios"),
    path("usuarios/eliminar/<int:pk>/", usuario_eliminar, name="usuario-eliminar"),
    path("usuarios/editar/<int:pk>/", usuario_editar, name="usuario-editar")
]

clasificacion/models.py
from django.db import models

# Create your models here.

comunidad/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

def get_image_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{instance.documento}.{ext}"
    return f"comunidad/usuarios/{filename}"
# Create your models here.
class Usuario(models.Model):
    primer_nombre= models.CharField(max_length=45,verbose_name="Primer Nombre")
    segundo_nombre= models.CharField(max_length=45,verbose_name="Segundo Nombre", blank=True,null=True)

    primer_apellido= models.CharField(max_length=45,verbose_name="Primer Apellido")
    segundo_apellido= models.CharField(max_length=45,verbose_name="Segundo Apellido")
    
    fecha_nacimiento= models.DateField(verbose_name="Fecha de Nacimiento")
    imagen = models.ImageField(upload_to=get_image_filename, blank=True, null=True,default="comunidad\def-user.png")
    correo = models.EmailField(max_length=50, verbose_name="Correo")
    
    class Rol(models.TextChoices):
        ADMINISTRADOR="AD",_("Administrador")
        TRABAJADORES="TR",_("Trabajador")
    rol=models.CharField(max_length=2,choices=Rol.choices,default=Rol.ADMINISTRADOR,verbose_name="Rol")
    class TipoDocumento(models.TextChoices):
        CEDULA='CC',_("Cédula")
        TARJETA='TI',_("Tarjeta de Identidad")
        CEDULA_EXTRANJERIA='CE',_("Cédula de Extrangería")
    tipo_documento=models.CharField(max_length=2,choices=TipoDocumento.choices,verbose_name="Tipo de Documento")
    documento= models.PositiveIntegerField(verbose_name="Documento", unique=True)
    estado=models.BooleanField(default=True)
    def clean(self):
        self.primer_nombre= self.primer_nombre.title()
    def __str__(self):
        return f"{self.primer_nombre} {self.primer_apellido}"
    class Meta:
        verbose_name_plural="Usuarios"
    @property
    def full_name(self):
        if self.segundo_nombre:
            return f"{self.primer_nombre} {self.segundo_nombre} {self.primer_apellido} {self.segundo_apellido}"
        else:
            return f"{self.primer_nombre} {self.primer_apellido} {self.segundo_apellido}" 

configuracion/models.py
from django.db import models

# Create your models here.
class Slider(models.Model):
    nombre= models.CharField(max_length=45,verbose_name="Nombre")
    descripcion= models.CharField(max_length=200,verbose_name="Descripción",blank=True, null=True)
    url= models.CharField(max_length=100,verbose_name="URL", blank=True, null=True)
    imagen = models.ImageField(upload_to='slider_images/')
    estado = models.BooleanField(default=True)
    
    def __str__(self):
        return self.nombre
    

operaciones/models.py
from django.db import models

# Create your models here.
from django.db import models

class AgendarCita(models.Model):
    # Campos del modelo AgendarCita
    fecha = models.DateField()
    hora = models.TimeField()
    nombre= models.CharField(max_length=100)
    motivo = models.TextField()

    def __str__(self):
        return f'Cita para {self.nombre} el {self.fecha} a las {self.hora}'

comunidad/forms.py
from django.forms import ModelForm, widgets
from comunidad.models import Usuario

class UsuarioForm(ModelForm):
    class Meta:
        model= Usuario
        fields= "__all__"
        exclude=["estado",]
        widgets={
            'fecha_nacimiento':widgets.DateInput(attrs={'type':'date'},format='%Y-%m-%d')
        }
        
class UsuarioEditarForm(ModelForm):
    class Meta:
        model= Usuario
        fields= "__all__"
        exclude=["estado", "fecha_nacimiento", "documento"]
        

base/views.py
from django.shortcuts import render
from configuracion.models import Slider

def principal(request):
    titulo="Bienvenido"
    sliders= Slider.objects.filter(estado=True)
    context={
        "titulo": titulo,
        "sliders": sliders
    }
    return render(request, "index.html", context)

def principal_admin(request):
    titulo="Bienvenido"
    context={
        "titulo": titulo,
    }
    return render(request, "index-admin.html", context)

def agendar_cita(request):
    # Tu lógica para agendar citas aquí
    return render(request, 'agendar_cita.html')    

comunidad/views.py
from django.shortcuts import render, redirect
from comunidad.forms import UsuarioForm, UsuarioEditarForm
from comunidad.models import Usuario
from django.contrib import messages
from PIL import Image
# Create your views here.
def usuario_crear(request):
    titulo="Usuario"
    accion="Agregar"
    usuarios= Usuario.objects.all()
    if request.method=="POST":
        form= UsuarioForm(request.POST,request.FILES)
        if form.is_valid():
            usuario= form.save()
            if usuario.imagen:
                img = Image.open(usuario.imagen.path)
                img= img.resize((500,500))
                img.save(usuario.imagen.path)
            usuario.save()
            messages.success(request, f'¡El Usuario se agregó de forma exitosa!')
            return redirect("usuarios")
        else:
            messages.danger(request, f'¡ Error al agregar al Usuario!')
            pass
    else:
        form=UsuarioForm()
    context={
        "titulo":titulo,
        "usuarios":usuarios,
        "form":form,
        "accion":accion,
    }
    return render(request,"comunidad/usuarios/usuarios.html", context)  

def usuario_editar(request,pk):
    usuario= Usuario.objects.get(id=pk)
    usuarios= Usuario.objects.all()
    accion="Editar"
    nombre=f"{usuario.primer_nombre} {usuario.primer_apellido}"
    titulo=f"Usuario {usuario.id} {nombre}"
    
    if request.method=="POST":
        form= UsuarioEditarForm(request.POST,request.FILES, instance=usuario)
        if form.is_valid():
            usuario= form.save()
            if usuario.imagen:
                img = Image.open(usuario.imagen.path)
                img= img.resize((500,500))
                img.save(usuario.imagen.path)
            usuario.save()
            messages.success(request, f'¡{nombre} se editó de forma exitosa!')
            return redirect("usuarios")
        else:
            messages.danger(request, f'¡Error al editar {nombre}!')
            pass
    else:
        form=UsuarioEditarForm(instance=usuario)
    context={
        "titulo":titulo,
        "usuarios":usuarios,
        "form":form,
        "accion":accion
    }
    return render(request,"comunidad/usuarios/usuarios.html", context)
  
def usuario_eliminar(request,pk):
    usuario=Usuario.objects.filter(id=pk)
    usuario.update(estado=False)
    
    ## Agregar mensaje de exito
    return redirect('usuarios') 

def agendar_cita(request):
    # Lógica para agendar la cita
    return render(request, 'agendar_cita.html')


    

configuracion/views.py
from django.shortcuts import render

# Create your views here.

operaciones/views.py
from django.shortcuts import render


def agendar_cita(request):
    # Tu lógica para agendar citas aquí
    return render(request, 'agendar_cita.html')

base/templates/agendar_cita.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendar Cita</title>
    <!-- Agrega aquí tus enlaces a tus archivos CSS, si es necesario -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<style>
    body {
        background-image: url('/static/img/hamaca.jpeg'); /* Ruta de la imagen */
        background-size: cover; /* Cubrir todo el cuerpo */
        background-repeat: no-repeat; /* No repetir la imagen */
        background-position: center; /* Centrar la imagen */
    }

    .bg-custom-gray-light {
        background-color: #FAD7A0;
    }
    
</style>
<body>
    <div class="container">
        <div class="row justify-content-between mt-3">
            <div class="col-md-6">
                <!-- Agrega tu botón en la parte superior izquierda -->
            </div>
            <div class="col-md-6 text-right">
                <!-- Agrega tu botón en la parte superior derecha -->
                <a href="{% url 'index' %}" class="btn btn-dark">Regresar al Inicio</a>
            </div>
        </div>
    </div>
    
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card bg-custom-gray-light">
                    <div class="card-body">
                        <h1 class="card-title text-center">Agendar Cita</h1>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="paciente">Nombre:</label>
                                <input type="text" id="nombre" name="nombre" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="paciente">Telefono:</label>
                                <input type="text" id="nombre" name="nombre" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="fecha">Fecha:</label>
                                <input type="date" id="fecha" name="fecha" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="hora">Hora:</label>
                                <input type="time" id="hora" name="hora" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="direccion">Dirección:</label>
                                <input type="text" id="direccion" name="direccion" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="ciudad">Ciudad:</label>
                                <input type="text" id="ciudad" name="ciudad" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="motivo">Servicio:</label>
                                <textarea id="motivo" name="motivo" class="form-control"></textarea>
                            </div>
                            <button type="submit" class="btn btn-dark btn-block">Agendar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Agrega aquí tus enlaces a tus archivos JavaScript, si es necesario -->
</body>
<script>
    // Función para mostrar una notificación
    function mostrarNotificacion(mensaje, tipo) {
        // Crear un elemento de alerta
        var alerta = document.createElement('div');
        alerta.classList.add('alert', 'alert-' + tipo);
        alerta.textContent = mensaje;
    
        // Agregar la alerta al contenedor de notificaciones
        document.getElementById('notificaciones').appendChild(alerta);
    
        // Desaparecer la alerta después de 5 segundos
        setTimeout(function() {
            alerta.remove();
        }, 5000);
    }
    </script>
    
</html>

base/templates/comunidad/usuarios/usuarios.html
{% extends 'partials/admin/body.html' %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}

{% block contenido %}
<div class="container-fluid m-4 row">
    <div class="rounded card p-3 col-md-3">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-success" type="submit"
                value="{{accion}} {{titulo}}">
            <a href="{% url 'usuarios' %}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
    <div class="rounded card p-4 mx-4 col-md-8">
        <table class="table table-bordered w-100 display nowrap" id="tabla-usuarios">
            <thead>
                <tr>
                    
                    <th scope="col">Imagen</th>
                    <th scope="col">Primer Nombre</th>
                    <th scope="col">Segundo Nombre</th>
                    <th scope="col">Primer Apellido</th>
                    <th scope="col">Segundo Apellido</th>
                    <th scope="col">Fecha de Nacimiento</th>
                    <th scope="col">Rol</th>
                    <th scope="col">Tipo de Documento</th>
                    <th scope="col">Documento</th>
                    <th>Accion</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}

                {% if  usuario.estado %}

                
                <tr>
                    <td>
                        <img src="{{ usuario.imagen.url }}"
                            class="img-circle elevation-2" alt="User Image"
                            width="60"/>
                    </td>
                    
                    <td>{{ usuario.primer_nombre }}</td>
                    <td>{{ usuario.segundo_nombre }}</td>
                    <td>{{ usuario.primer_apellido }}</td>
                    <td>{{ usuario.segundo_apellido }}</td>
                    <td>{{ usuario.fecha_nacimiento }}</td>
                    <td>{{ usuario.get_rol_display }}</td>
                    <td>{{ usuario.get_tipo_documento_display }}</td>
                    <td>{{ usuario.documento }}</td>
                    <td>
                        <button type="button" class="btn btn-danger"
                            data-bs-toggle="modal"
                            data-bs-target="#staticBackdrop{{usuario.id}}"
                            data-bs-toggle="tooltip" title="Eliminar">
                            {% bs_icon 'trash' %}
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="staticBackdrop{{usuario.id}}"
                            data-bs-backdrop="static" data-bs-keyboard="false"
                            tabindex="-1" aria-labelledby="staticBackdropLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5"
                                            id="staticBackdropLabel">Esta seguro
                                            de eliminar el {{ titulo }}</h1>
                                        <button type="button" class="btn-close"
                                            data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Una vez eliminado no hay marcha atras
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button"
                                            class="btn btn-secondary"
                                            data-bs-dismiss="modal">Cancelar</button>
                                        <a href="{% url 'usuario-eliminar' usuario.id %}"
                                            class="btn btn-primary">Eliminalo!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'usuario-editar' usuario.id %}" class="btn btn-primary"
                            data-bs-toggle="tooltip" data-bs-placement="top"
                            title="Editar">{% bs_icon 'pencil' %}</a></td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>

    </div>
    

</div>

{% endblock contenido %}

base/templates/index-admin.html
{% extends 'partials/admin/body.html' %}
{% block contenido %}
{% load bootstrap_icons %}
{% load static %}

  <!-- Info boxes -->
  <div class="row">
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box">
        <span class="info-box-icon bg-info elevation-1">
          {% bs_icon 'person' size='1.5em'%}</i></span>

        <div class="info-box-content">
          <span class="info-box-text">Usuarios</span>
          <span class="info-box-number">{{ usuarios_cantidad }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-danger elevation-1">{% bs_icon 'shop' size='1.5em'%}</i></span>

        <div class="info-box-content">
            
          <span class="info-box-text">Agenda</span>
          <span class="info-box-number">{{tiendas_cantidad}}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-success elevation-1">{% bs_icon 'box-seam-fill' size='1.5em'%}</i></span>

        <div class="info-box-content">
          <span class="info-box-text">Productos</span>
          <span class="info-box-number">{{ productos_cantidad }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-warning elevation-1">{% bs_icon 'basket-fill' size='1.5em'%}</i></span>

        <div class="info-box-content">
          <span class="info-box-text">Pedidos</span>
          <span class="info-box-number">{{pedidos_cantidad}}</span>
        </div>

        <div class="info-box-content">
          <span class="info-box-text">Fotos</span>
          <span class="info-box-number">{{fotos_cantidad}}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
 <div class="card w-50 mx-auto p-4">
  <div class="h3">Citas Programadas</div>
  <canvas id="chart-Usuarios"></canvas>
</div>
</div>

<script src="{% static 'ChartJS/chart.js' %}"></script>
<script> src="https://cdn.jsdelivr.net/npm/chart.js"</script>
<script src="{% static 'ChartJS/MyCharts/chart-usuarios.js' %}"></script>


{% endblock %}

base/templates/index.html
{% extends 'partials/body.html' %}
{% load bootstrap_icons %}
{% load static %}

{% block contenido %}
  <!-- Enlaces a los archivos de Bootstrap CSS y JS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-pzjw8f+wh6m1zNz9zBKE8sFkXv4r4NRpDWddl1EaS7kRKtkwILtfdz1G2EnoWSgI" crossorigin="anonymous">
  <!-- Iconos de Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
  <!-- En tu archivo HTML -->

  <style>
    /* Estilos para los iconos */
    .icono {
      color: black; /* Color del icono */
      font-size: 24px; /* Tamaño del icono */
      margin-right: 10px; /* Espacio entre icono y texto */
    }

    /* Estilos para la barra de iconos fija */
    .navbar-icons {
      position: fixed;
      top: 50%;
      right: 0;
      transform: translateY(-50%);
      z-index: 1000; /* Asegura que los iconos estén por encima del contenido */
      background-color: #ABB2B9; /* Fondo blanco para que los iconos sean visibles */
      padding: 10px; /* Espacio interno */
    }
    

  </style>
<main class="overflow-hidden">

  <div id="carouselExampleCaptions" class="carousel slide" >
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">

      <div class="carousel-item active ">
        <img src="static\img\escritorio.jpeg" class="d-block w-100" alt="">
        <div class="carousel-caption d-none d-md-block">
          <h3 style="color: #000000;">Bienvenido</h3>
        </div>
      </div>
      <div class="carousel-item">
        <img src="static\img\vista2.jpeg" class="d-block w-100" alt="">
        <div class="carousel-caption d-none d-md-block">
          <h3 style="color: #000000;">Pequeño paraíso.</h3>
          <h5 style="color: #000000;">Un espacio diseñado para relajarse y desconectar de la rutina.</h5>
        </div>
      </div>
      <div class="carousel-item">
        <img src="static\img\mesadecocina.jpeg" class="d-block w-100" alt="">
        <div class="carousel-caption d-none d-md-block">
          <h3 style="color: #000000;">Perfección funcionalidad y estética</h3>
          <h5 style="color: #000000;">Atmósfera acogedora que resalta los detalles arquitectónicos.</h5>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <ul class="navbar-nav ms-auto navbar-icons" style="color: black; font-size: 24px; margin-right: 10px;"> <!-- Aquí se aplica la clase .navbar-icons -->
    <li class="nav-item">
      <button class="nav-link btn" onclick="changeContrast()"title="Cambiar contraste"><i class="fas fa-adjust icono"></i></button>
    </li>
    <li class="nav-item">
      <button class="nav-link btn" onclick="increaseFontSize()" title="Aumentar tamaño de letra">
          <i class="fas fa-plus icono"></i>
      </button>
  </li>
  
    <li class="nav-item">
      <button class="nav-link btn" onclick="decreaseFontSize()" title="Disminuir tamaño de letra"><i class="fas fa-minus icono"></i></button>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#top" title="Ir arriba"><i class="fas fa-chevron-up icono"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#bottom" title="Ir abajo"><i class="fas fa-chevron-down icono"></i></a>
    </li>
  </ul>
  
  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
          xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"><title>Placeholder</title><rect width="100%"
            height="100%" fill="var(--bs-secondary-color)"></rect></svg>
        <h2 class="fw-normal">Heading</h2>
        <p>Some representative placeholder content for the three columns of text
          below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
          xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"><title>Placeholder</title><rect width="100%"
            height="100%" fill="var(--bs-secondary-color)"></rect></svg>
        <h2 class="fw-normal">Heading</h2>
        <p>Another exciting bit of representative placeholder content. This
          time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
          xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"><title>Placeholder</title><rect width="100%"
            height="100%" fill="var(--bs-secondary-color)"></rect></svg>
        <h2 class="fw-normal">Heading</h2>
        <p>And lastly this, the third column of representative placeholder
          content.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->

    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider" />
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">
                Espacios
                <span class="text-muted">Iluminados.</span>
            </h2>
            <p class="lead">
                Ofrecemos servicios de diseño de interiores para casas y apartamentos, 
                creando espacios que reflejan la personalidad y estilo de vida de nuestros clientes.
                Analizamos las necesidades de cada proyecto y proponemos soluciones creativas e innovadoras 
                para sacar el máximo provecho a los espacios disponibles. 
                Contamos con un equipo de diseñadores expertos 
                en tendencias y materiales, que se encargará de cada detalle para lograr ambientes modernos,
                funcionales y estéticamente agradables. ¡Hagamos de tu hogar un reflejo de quién eres!

.
            </p>
        </div>
        <div class="col-md-5">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                height="500" src="{% static 'img/comedor.jpeg' %}" role="img" aria-label="Placeholder: 500x500"
                preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title>
        </img>
        </div>
    </div>
    <hr class="featurette-divider" />
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">
                Aprovechamiento<span class="text-muted"> e innovación</span>
            </h2>
            <p class="lead">
                Reinventamos ambientes aplicando conceptos de diseño sostenible,
                aprovechando materiales reciclados y amigables con el medio ambiente.
                Realizamos remodelaciones integrales con visión funcional, estética y ecológica. 
                Proponemos soluciones como: aprovechamiento de luz natural,
                sistemas de ahorro de energía, materiales no tóxicos, entre otros.
    
            </p>
        </div>
        <div class="col-md-5 order-md-1">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                height="500" src="{% static 'img/balcon.jpeg' %}" role="img" aria-label="Placeholder: 500x500"
                preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title>
            </img>
        </div>
    </div>
    <hr class="featurette-divider" />
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">
                Practicidad <span class="text-muted">y distinción.</span>
            </h2>
            <p class="lead">
                Rediseñamos y renovamos baños creando espacios únicos y funcionales
                que se adaptan a los gustos y necesidades de nuestros clientes.
                Complementamos el diseño con espejos, iluminación y accesorios vanguardistas.
                Ofrecemos instalación profesional garantizada. Transformamos estos espacios en piezas centrales que impresionan por su belleza,
                practicidad y distinción.
            </p>
        </div>
        <div class="col-md-5">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                height="500" src="{% static 'img/espejo.jpeg' %}" role="img" aria-label="Placeholder: 500x500"
                preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title>
            </img>
        </div>
    </div>
    <hr class="featurette-divider" />
</div><!-- /.container -->
<script src="{% static 'accesibility.js' %}"></script>

</main>

{% endblock contenido %}